In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop('species', axis=1)
y = df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [12]:
from sklearn.model_selection import cross_val_score

In [13]:
model_knn.score(X_test,y_test)

1.0

In [14]:
from sklearn.svm import SVC

In [15]:
model_svm = SVC(gamma='auto')

In [16]:
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [17]:
model_svm.score(X_test,y_test)

1.0

In [18]:
 #now lets use grid search cv

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
classifer = GridSearchCV((model_svm), {
    "C":[1,10,20,30],
    'kernel':['rbf','linear']
},cv = 5,return_train_score = False)

In [21]:
classifer.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [22]:
classifer.cv_results_

{'mean_fit_time': array([0.00279579, 0.00291562, 0.00266356, 0.00262079, 0.00273137,
        0.00281301, 0.0026155 , 0.00248137]),
 'std_fit_time': array([3.75134845e-04, 4.97897391e-04, 2.86330664e-04, 4.61866859e-04,
        3.92780044e-04, 1.53433172e-04, 4.39925631e-05, 1.33064961e-04]),
 'mean_score_time': array([0.00233121, 0.00175123, 0.00203977, 0.00187926, 0.00197425,
        0.00192666, 0.00207314, 0.00186796]),
 'std_score_time': array([1.31282233e-04, 2.47695420e-04, 2.25167616e-04, 3.11698548e-04,
        3.11812295e-04, 1.56887179e-04, 9.17651524e-05, 2.08921585e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [23]:
results = pd.DataFrame(classifer.cv_results_)

In [24]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002796      0.000375  ...        0.016330                1
1       0.002916      0.000498  ...        0.016330                1
2       0.002664      0.000286  ...        0.016330                1
3       0.002621      0.000462  ...        0.038873                4
4       0.002731      0.000393  ...        0.036515                5
5       0.002813      0.000153  ...        0.042164                6
6       0.002615      0.000044  ...        0.038873                7
7       0.002481      0.000133  ...        0.048990                7

[8 rows x 15 columns]

In [25]:
cls = GridSearchCV((model_knn), {
    'n_neighbors': [3,5,7,33,23],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
},cv = 5, return_train_score=False)

In [26]:
cls.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 33, 23],
                         'weights': ['uniform', 'distance']})

In [27]:
rs = cls.cv_results_

In [28]:
out = pd.DataFrame(cls.cv_results_)

In [29]:
out[['param_algorithm', 'param_n_neighbors',	'param_weights', 'mean_test_score']]

   param_algorithm  param_n_neighbors param_weights  mean_test_score
0             auto                  3       uniform         0.966667
1             auto                  3      distance         0.966667
2             auto                  5       uniform         0.973333
3             auto                  5      distance         0.966667
4             auto                  7       uniform         0.980000
5             auto                  7      distance         0.980000
6             auto                 33       uniform         0.940000
7             auto                 33      distance         0.966667
8             auto                 23       uniform         0.960000
9             auto                 23      distance         0.980000
10       ball_tree                  3       uniform         0.966667
11       ball_tree                  3      distance         0.966667
12       ball_tree                  5       uniform         0.973333
13       ball_tree                  5      distance         0.966667
14       ball_tree                  7       uniform         0.980000
15       ball_tree                  7      distance         0.980000
16       ball_tree                 33       uniform         0.940000
17       ball_tree                 33      distance         0.966667
18       ball_tree                 23       uniform         0.960000
19       ball_tree                 23      distance         0.980000
20         kd_tree                  3       uniform         0.966667
21         kd_tree                  3      distance         0.966667
22         kd_tree                  5       uniform         0.973333
23         kd_tree                  5      distance         0.966667
24         kd_tree                  7       uniform         0.980000
25         kd_tree                  7      distance         0.980000
26         kd_tree                 33       uniform         0.940000
27         kd_tree                 33      distance         0.966667
28         kd_tree                 23       uniform         0.960000
29         kd_tree                 23      distance         0.980000
30           brute                  3       uniform         0.966667
31           brute                  3      distance         0.966667
32           brute                  5       uniform         0.973333
33           brute                  5      distance         0.966667
34           brute                  7       uniform         0.980000
35           brute                  7      distance         0.980000
36           brute                 33       uniform         0.940000
37           brute                 33      distance         0.966667
38           brute                 23       uniform         0.960000
39           brute                 23      distance         0.980000

In [1]:
from sklearn.model_selection import RandomizedSearchCV

In [30]:
rand = RandomizedSearchCV((model_knn), {
    'n_neighbors': [3,5,7,33,23],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
},n_iter=5,cv = 5, return_train_score=False)

In [31]:
rand.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
                   n_iter=5,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [3, 5, 7, 33, 23],
                                        'weights': ['uniform', 'distance']})

In [32]:
result = pd.DataFrame(rand.cv_results_)

In [34]:
result[['param_weights', 'param_n_neighbors',	'param_algorithm', 'mean_test_score']]

  param_weights  param_n_neighbors param_algorithm  mean_test_score
0       uniform                  3         kd_tree         0.966667
1      distance                 23       ball_tree         0.980000
2      distance                  5            auto         0.966667
3       uniform                  3           brute         0.966667
4      distance                 33         kd_tree         0.966667